# Generated by Django 4.1.7 on 2023-04-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='nick_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
