# Generated by Django 4.1.7 on 2023-04-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_reg', '0002_alter_account_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\stasm\\PycharmProjects\\Test_TEB\\register_tel\\media'),
        ),
    ]
