# Generated by Django 4.1.7 on 2023-04-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_reg', '0003_alter_account_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
