# Generated by Django 4.1.7 on 2023-04-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_reg', '0007_alter_account_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo_url',
            field=models.FilePathField(blank=True, null=True, path='C:\\Users\\stasm\\PycharmProjects\\Test_TEB\\register_tel\\media'),
        ),
    ]
